export const BookingsTable = [
    {
      fname: 'Tony',
      lname:"Starc",
      location1: 'Belmont',
      location2: 'North Carolina',
      contact: "+1 012 345 6789",
      Ftime:'10:30 AM',
      Fdate:'May 3, 2023',
      Ttime:'11:30 AM',
      Tdate:'May 3, 2023',
      type: "Truck Parking" ,
      amount:'$5',
      status: 'Paid',
      threedots: '/media/icons/cardIcons/threeDots.svg',
    },
    {
      fname: 'Tony',
      lname:"Starc",
      location1: 'Belmont',
      location2: 'North Carolina',
      contact: "+1 012 345 6789",
      Ftime:'10:30 AM',
      Fdate:'May 3, 2023',
      Ttime:'11:30 AM',
      Tdate:'May 3, 2023',
      type: "Truck Parking" ,
      amount:'$5',
      status: 'Paid',
      threedots: '/media/icons/cardIcons/threeDots.svg',
    },
    {
        fname: 'Tony',
        lname:"Starc",
        location1: 'Belmont',
        location2: 'North Carolina',
        contact: "+1 012 345 6789",
        Ftime:'10:30 AM',
        Fdate:'May 3, 2023',
        Ttime:'11:30 AM',
        Tdate:'May 3, 2023',
        type: "Truck Parking" ,
        amount:'$5',
        status: 'Paid',
        threedots: '/media/icons/cardIcons/threeDots.svg',
      },
    {
      fname: 'Tony',
      lname:"Starc",
      location1: 'Belmont',
      location2: 'North Carolina',
      contact: "+1 012 345 6789",
      Ftime:'10:30 AM',
      Fdate:'May 3, 2023',
      Ttime:'11:30 AM',
      Tdate:'May 3, 2023',
      type: "Truck Parking" ,
      amount:'$5',
      status: 'Paid',
      threedots: '/media/icons/cardIcons/threeDots.svg',
    },
    {
      fname: 'Tony',
      lname:"Starc",
      location1: 'Belmont',
      location2: 'North Carolina',
      contact: "+1 012 345 6789",
      Ftime:'10:30 AM',
      Fdate:'May 3, 2023',
      Ttime:'11:30 AM',
      Tdate:'May 3, 2023',
      type: "Truck Parking" ,
      amount:'$5',
      status: 'Paid',
      threedots: '/media/icons/cardIcons/threeDots.svg',
    },

  ];